---
title: hexagon
timezone: UTC
collections:
  selected-projects:
    title: Selected projects
    output: true
  uploads:
    title: Uploads
    output: true

defaults:

- scope:
    path: '/selected-projects/mayfair-apartment/'
    type: selected-project
  values:
    layout: selected-project
